apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-xmsa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-xmsa
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-xmsa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-xmsa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-xmsa
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qadn-tenant/nodejs-users/simple-nodejs-app-xmsa@sha256:978636918c87879b9366e709610bea1d1c69525f21160e07da55713cea25527b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
